export const walletOne = [
  {
    id: 2,
    sym: "erc20",
    name: "Ethereum",
    address: "0xA3c9c8a2466107E9BFD2C067c2DC37F18559dA2b",
    network: "Eth",
    img: "",
  },
  {
    id: 3,
    sym: "usdt",
    name: "Tether ",
    address: "TVdAzHK24oAa92FcGReEexRa59v4KCquwP",
    network: "usdt",
    img: "",
  },
  {
    id: 1,
    sym: "btc",
    name: "Bitcoin",
    address: "bc1qkjz2mtfhg6f7fjr2vmtjx7hxmejzfes2jcqyvp",
    network: "BTC",
    img: "",
  },
  {
    id: 4,
    sym: "ltc",
    name: "Litecoin",
    address: "MPp8dz1oMUsr641GjFNeKNCEJJGQnBoZ3p",
    network: "litecoin",
    img: "",
  },
  {
    id: 5,
    sym: "BNB",
    name: "BNB",
    address: "bnb1elx3at8cs5f3gmsv0m099aezw2537grhp0wq8v",
    network: "BNB",
    img: "",
  },
];

export const walletTwo = [
  {
    id: 2,
    sym: "erc20",
    name: "Ethereum",
    address: "0xA3c9c8a2466107E9BFD2C067c2DC37F18559dA2b",
    network: "Eth",
    img: "",
  },
  {
    id: 3,
    sym: "usdt",
    name: "Tether ",
    address: "TVdAzHK24oAa92FcGReEexRa59v4KCquwP",
    network: "usdt",
    img: "",
  },
  {
    id: 1,
    sym: "btc",
    name: "Bitcoin",
    address: "bc1qkjz2mtfhg6f7fjr2vmtjx7hxmejzfes2jcqyvp",
    network: "BTC",
    img: "",
  },
  {
    id: 4,
    sym: "ltc",
    name: "Litecoin",
    address: "MPp8dz1oMUsr641GjFNeKNCEJJGQnBoZ3p",
    network: "litecoin",
    img: "",
  },
  {
    id: 5,
    sym: "BNB",
    name: "BNB",
    address: "bnb1elx3at8cs5f3gmsv0m099aezw2537grhp0wq8v",
    network: "BNB",
    img: "",
  },
];

